Common/PlayerCommon/CollisionPlayer.cs, Common/TileCommon/Corruption/ConversionHandler.cs, Common/TileCommon/Corruption/TileCorruptionGlobalTile.cs, Common/TileCommon/PresetTiles/Furniture/ChestTile.cs, Common/TileCommon/TileExtensions.cs, Common/WallCommon/IAutoloadUnsafeWall.cs, Content/Desert/CactusStaff/CactusWallProj.cs, Content/Forest/FairyWhistle/FairyWhistle.cs, Content/Forest/RoguesCrest/RogueKnifeMinion.cs, Content/Ocean/Items/Reefhunter/Buffs/EmpoweredSwim.cs, Content/Ocean/Items/Reefhunter/OceanPendant/OceanPendant.cs, Content/Savanna/Biome/SavannaBiome.cs, Content/Savanna/Ecotone/BaobabGen.cs, Content/Savanna/Ecotone/SavannaEcotone.cs, Content/Savanna/Items/CampfireSpit.cs, Content/Savanna/Tiles/AcaciaTree/TreetopPlatform.cs, Content/Savanna/Walls/LivingBaobabLeafWall.cs, Content/Savanna/Walls/LivingBaobabWall.cs, Content/Savanna/Walls/SavannaDirtWall.cs, Content/Underground/Zipline/ZiplineHandler.cs
- Reduced Savanna biome priority
- Made Cactus Staff projectiles draw behind tiles
- Made Rogue's Crest minion animate continuously
- Ensured the player's rotation is reset after death
- Made Fairy Whistle overwrite the Classic version
- Fixed Pirate Chest being unlockable without a key when Classic is enabled
- Improved Acacia Treetop grapple detection with the Squirrel Hook
- Made player-placed Coarse Dirt Walls safe
- Prevented custom tile corruption logic from running for unrelated tile types
- Fixed a drawing error with Stone Platforms
=> Various fixes

Common/ModCompat/Classic/SpiritClassic.cs, Common/ModCompat/FablesCompat.cs, Common/TileCommon/PresetTiles/SingleSlotEntity.cs, Common/Visuals/ForceWaterStyle.cs, Common/WorldGeneration/Ecotones/EcotoneEdgeDefinition.cs, Common/WorldGeneration/Micropasses/Passes/FishingAreaMicropass.cs, Common/WorldGeneration/WorldBoundAttribute.cs, Content/Forest/Botanist/Tiles/Scarecrow.cs, Content/Jungle/Bamboo/Tiles/BambooBirdCage.cs, Content/Jungle/Bamboo/Tiles/StrippedBamboo.cs, Content/Ocean/Items/KoiTotem/KoiTotem.cs, Content/Ocean/Items/MineralSlag.cs, Content/Ocean/Items/SunkenTreasure.cs, Content/Ocean/Tiles/Driftwood.cs, Content/Ocean/Tiles/Furniture/DriftwoodWorkBench.cs, Content/Savanna/Biome/SavannaBiome.cs, Content/Savanna/Ecotone/SavannaEcotone.cs, Content/Savanna/Items/CampfireSpit.cs, Content/Savanna/Tiles/SavannaDirt.cs, Content/Underground/Zipline/ZipRemovalData.cs, Content/Underground/Zipline/Zipline.cs, Content/Underground/Zipline/ZiplineGun.cs, Content/Underground/Zipline/ZiplineHandler.cs, Content/Underground/Zipline/ZiplineProj.cs, Localization/en-US_Mods.SpiritReforged.Items.hjson
- Fixed a crash caused by nearby Koi Totems when fishing
- Fixed a potential crash when loading mod water styles
- Included alternate jungle grass types in Ecotone surface mapping
- Fixed Scarecrow item drops syncing incorrectly in multiplayer
- Increased Savanna scene weight slightly
- Included "Well Fed" buff descriptions for several items
- Rail-Gun rails no longer persist when switching worlds
- Sunken Treasure no longer modifies framing of surface tiles when placed
=> Misc fixes

Common/ItemCommon/Backpacks/BackpackPlayer.cs, Common/UI/BackpackInterface/BackbackUISlot.cs, Common/UI/BackpackInterface/BackpackUIState.cs
- Adds in dye slot for backpacks
Note that this may also dye other things, but in 99% of cases the back and front slots will be used by backpacks unless some really weird crossmod code is happening.
- Syncs backpacks fully in mp - change visibility, unequip, equip, dye & undye with no inconsistencies
=> Dyeable backpacks

Common/TileCommon/PresetTiles/SingleSlotEntity.cs, Content/Forest/Botanist/Tiles/Scarecrow.cs, Content/Jungle/Bamboo/Tiles/BambooBirdCage.cs, Content/Savanna/Items/CampfireSpit.cs
Fixes a crash caused by Scarecrow when destroyed with a hat equipped in multiplayer + included an additional tile helper.
=> Scarecrow fix

Content/Forest/ButterflyStaff/ButterflyMinion.cs, Content/Jungle/Toucane/ToucanMinion.cs, Content/Ocean/Items/JellyfishStaff/JellyfishBolt.cs, Content/Ocean/Items/JellyfishStaff/JellyfishMinion.cs, Content/Ocean/Items/JellyfishStaff/JellyfishStaff.cs
Jellyfish Staff:
- Reduced pitch on SFX
- Increased the range of the chain lightning by 9%, number of chain targets by 1
- Increased damage by 1
- Reduced time between dashes from 1 second to 2/3 of a second
- Reduced the damage falloff per chained enemy from .8 of the original damage to .9 
Butterfly Staff:
- Made the butterfly more aggressive and more likely to quickly attack foes instead of spinning around them
Toucane:
- Increased maximum dash speed slightly
- Increased damage of feathers from .8 minion damage to just whatever the damage is
- increased the firing speed of feathers, thereby increasing the overall attack speed
=> Minion Tweaks/Buffs

Common/ModCompat/ThoriumCompat.cs, Content/Forest/Cloud/Items/CloudstalkSeed.cs, Content/Ocean/Items/FishCrate.cs, Content/Ocean/Items/SunkenTreasure.cs
NOTE: Waiting on Diver's permission before pushing to master pls 
A patch that introduces deliberate crossmod compatibility between Spirit and Thorium, as follows:
- Add Hat Fish and Subterranean Bulb to Packing Crate pool
- Make Man O’ War drop Jellyfish Staff
- Make Raging Minotaurs drop Leather
- If Eye of Cthulhu is defeated, Cobbler sells Explorer’s Treads
- Druid sells Cloudstalk Seeds after Eye of Cthulhu is defeated
- Baobab Leaves drop Living Leaves
- Sunken Treasure has Aquamarine and Opal in its loot pools
=> Thorium compat

Common/ModCompat/Classic/ModifyNPCData.cs, Content/Ocean/Items/PirateKey.cs, Content/Vanilla/Food/RawFish.cs
- As per a compat report in main, Spirit Classic enemies no longer drop Raw Fish, and Classic Raw Fish is now shimmerable
=> Make Classic Raw Fish Unobtainable

Common/TileCommon/PresetTiles/PotTile.cs, Content/Underground/Tiles/AetherShipment.cs, Content/Underground/Tiles/BiomePots.cs, Content/Underground/Tiles/ScryingPot.cs, Content/Underground/Tiles/SilverFoodPlatter.cs, Content/Underground/Tiles/SilverPlatters.cs, Content/Underground/Tiles/StuffedPots.cs, Content/Underground/Tiles/WormPot.cs, Localization/en-US/Mods.SpiritReforged.Items.hjson, Localization/en-US/Mods.SpiritReforged.Tiles.hjson, Localization/pt-BR/Mods.SpiritReforged.Items.hjson, Localization/pt-BR/Mods.SpiritReforged.Tiles.hjson, Localization/ru-RU/Mods.SpiritReforged.Items.hjson, Localization/ru-RU/Mods.SpiritReforged.Tiles.hjson, Localization/zh-Hans/Mods.SpiritReforged.Items.hjson, Localization/zh-Hans/Mods.SpiritReforged.Tiles.hjson
- Made Pots metal detectable
- Added AddMapData(), a method that allows pottiles to have custom map data easily
- Updated map colors for uncommon pots
- Updated map colors and names for rare pots
- Scrying Pot Loot: now drops one 'sight' related potion and silver coins
=> Pot Tweaks

Common/ItemCommon/ClubItem.cs, Common/ProjectileCommon/Abstract/BaseClubCommon.cs, Common/ProjectileCommon/Abstract/BaseClubProj.cs, Common/ProjectileCommon/Abstract/BaseClubVirtual.cs, Content/Forest/WoodClub/WoodClubProj.cs, Content/Particles/Shatter.cs, Content/Underground/Items/OreClubs/GoldClubProj.cs, Content/Underground/Items/OreClubs/PlatinumClubProj.cs, Localization/en-US/Mods.SpiritReforged.Items.hjson
-Allows clubs to properly scale with melee size modifiers, including hide tunic
-Some slight reorganization, instances of projectile.scale are now replaced with "TotalScale" or renamed to "BaseScale" when not using the total scale including modifiers, to add some clarity between the use cases
-Renames the ore clubs and gives them tooltips explaining how to use them
=> Club size modifiers

Common/PrimitiveRendering/TrailHelper.cs, Common/ProjectileCommon/Abstract/BaseClubProj.cs, Common/ProjectileCommon/Abstract/BaseClubVirtual.cs, Content/Underground/Items/OreClubs/GoldClubProj.cs
- Fixed `GoldClubProj` writing `Direction` as an unsigned value for syncing
- Fixed players always facing left to other clients when charging a club
- Prevented several `BaseClubProj` variables from syncing unnecessarily
- Prevented `TrailManager.ManualTrailSpawn` from syncing by default
=> Club multiplayer fixes

Common/NPCCommon/Abstract/WorldNPC.cs, Common/NPCCommon/ITravelNPC.cs, Content/Forest/Misc/Cartographer.cs, Content/Forest/Misc/Hiker.cs
- Adds a system for handling traveling NPCs
- Makes the Cartographer randomly appear like the traveling merchant when any player owns a pin
- Increased Hiker and Cartographer base spawn rates by 25%
=> Traveling NPCs

Common/PrimitiveRendering/Trail_Components/ITrailColor.cs, Common/ProjectileCommon/Abstract/BombProjectile.cs, Content/Underground/Items/BombCannon.cs, Localization/en-US/Mods.SpiritReforged.Projectiles.hjson, Localization/pt-BR/Mods.SpiritReforged.Projectiles.hjson, Localization/ru-RU/Mods.SpiritReforged.Projectiles.hjson, Localization/zh-Hans/Mods.SpiritReforged.Projectiles.hjson
Greatly adjusts how bomb cannon works under the hood to allow for unique visuals, and the bomb doing contact damage, with nerfed explosion damage to compensate
Changes bomb cannon to use arc velocity calculation, and increases shot speed at low charge to be far more consistent
Bomb cannon is now classified as a ranged weapon and displays its damage range in the tooltip
=> Bomb cannon tweaks

Common/UI/PotCatalogue/CatalogueEntry.cs
Changes Potstiary icons to draw using PointClamp, which fixes artifacts at high zoom levels.
=> Potstiary zoom fix

Common/Misc/AchievementGlobalItem.cs, Common/SpiritSets.cs, Common/TileCommon/IAutoloadTileItem.cs, Common/TileCommon/PresetTiles/Furniture/FurnitureTile.cs, Common/WorldGeneration/Micropasses/CustomCaves.cs
- Adds TIMBER achievement to picking up Drywood
- Adds BENCHED achievement to picking up either Reforged workbench
- Undid debug rate for caves which made every single one of them a canyon
- Added StaticItemDefaults for IAutoloadTileItem, unused because ItemID.Sets.Workbenches is dumb
=> add timber to drywood pickup, benched to either bench craft, cleanup

Common/UI/PotCatalogue/CatalogueUI.cs, Content/Underground/Pottery/TileRecord.cs, Content/Underground/Tiles/BiomePots.cs, Content/Underground/Tiles/Pots.cs
Changes `TileRecord.hidden` from `bool` to `Func<bool>`. Hides Corruption/Crimson pot entries from the Potstiary on the opposite world evil unless unlocked.
=> Potstiary entry change

Common/ModCompat/CrossMod.cs, Common/WorldGeneration/Micropasses/Passes/ButterflyMicropass.cs, Common/WorldGeneration/Micropasses/Passes/FishingAreaMicropass.cs, Common/WorldGeneration/Micropasses/Passes/PotteryStructureMicropass.cs, Common/WorldGeneration/QuickConversion.cs, Content/Savanna/Ecotone/SavannaEcotone.cs
- Makes Fishing Coves & Pottery structures spawn at least 400 tiles away from the edges of the world with Remnants on, avoiding some poor overlapping biomes
- Moves Pottery structures down, which would poke out to the surface even on some vanilla small/medium worlds
- Stops Fishing Coves from placing over Granite and Marble
- Made the Savanna's Watering Holes spawn only if there's walls to hold in their water at the top
- Made Savanna population gen properly check `tile.HasTile`, stopping a TON (from 78,000 iterations to ~350) of useless checks, fixing Remnants population
- Made our automatic biome conversion more sensitive to jungles with Remnants
- Made Acacia trees spawn much more often with Remnants on
All of these changes are either for functionality or per wombat's (of Remnants) …
=> add a ton of checks for remnants

Common/Misc/EmoteHelper.cs, Common/NPCCommon/NPCHelper.cs, Content/Forest/Misc/ChairClub/BreakawayChairProj.cs, Localization/pt-BR/Mods.SpiritReforged.Items.hjson, Localization/ru-RU/Mods.SpiritReforged.Items.hjson, Localization/zh-Hans/Mods.SpiritReforged.Items.hjson
- Adds in EmoteHelper to help make NPCs emote
- Adds in EmoteHelper.SendNPCEmote to sync it
- Breakaway Chair makes NPCs use the "Angry" emote when hit
=> add emote helpers, breakaway chair makes npcs angry

Common/ConfigurationCommon/ReforgedClientConfig.cs, Common/Visuals/RenderTargets/ModTarget2D.cs, Common/Visuals/RenderTargets/TargetSetup.cs, Content/Ocean/OceanGeneration.cs, Content/SaltFlats/Tiles/Salt/SaltBlock.cs, Content/SaltFlats/Tiles/Salt/SaltBlockVisuals.cs, Localization/en-US/Mods.SpiritReforged.Configs.hjson, Localization/pt-BR/Mods.SpiritReforged.Configs.hjson, Localization/ru-RU/Mods.SpiritReforged.Configs.hjson, Localization/zh-Hans/Mods.SpiritReforged.Configs.hjson
- Adds config presets to change how reflections look on tiles
- Adds the ability for reflections to capture dusts, gores, projectiles and items on the highest preset
- Fixes reflections crashing the game on retro lighting modes
- Fixes `ModTarget2D` instances not resizing correctly
=> Tile reflection settings

Content/Savanna/SavannaGlobalNPC.cs, Content/Savanna/Tiles/AcaciaTree/AcaciaTree.cs
- Adds Grebes, 2 Dragonflies, and Scorpions as uncommon critter spawns in the Savanna
- Adds Birds and Spaarows as uncommon shaking spawns from Acacias
=> Add Critters to Savanna Spawns + Acacias

Common/Multiplayer/MultiplayerHandler.cs, Common/Multiplayer/PacketData.cs, Common/PlayerCommon/PlayerMouseHandler.cs, Content/Underground/Items/BombCannon.cs, Content/Underground/Items/ClayBomb.cs, Content/Underground/Items/ClayBombSticky.cs, Content/Underground/Items/CoarseBomb.cs, Content/Underground/Items/CoarseBombSticky.cs, Content/Underground/Items/FingerGun/FingerGun.cs, Content/Underground/Items/MudBomb.cs, Content/Underground/Items/MudBombSticky.cs, Content/Underground/Items/SandBomb.cs, Content/Underground/Items/SandBombSticky.cs, Content/Underground/NPCs/DunceCrab.cs, build.txt, changelog.txt
- Made all bombs not show up as ammo, not go into ammo slots
- Fixed Finger Blaster issue in mp
- Fixed Dunce Crabs embedding into air if the ground under them is mined out
- Fixed Dunce Crabs being desynced by a server issue
- Stopped ShareMouseData packet from noting sync in mp, spamming log
=> see changelog
