GabeHasWon/SpiritReforged

Common/WorldGeneration/Micropasses/Passes/FishingAreaMicropass.cs
Common/WorldGeneration/WorldBoundAttribute.cs
Content/Underground/Zipline/ZiplineHandler.cs
build.txt

fix WorldBoundAttribute not resetting collections

---

Common/WorldGeneration/Ecotones/EcotoneSurfaceMapping.cs
Content/Savanna/Ecotone/SavannaEcotone.cs
Localization/en-US/Mods.SpiritReforged.Generation.hjson
Localization/pt-BR/Mods.SpiritReforged.Generation.hjson
Localization/ru-RU/Mods.SpiritReforged.Generation.hjson

Fixes the Savanna generating with an offset + minor cleanup.

Savanna Ecotone mapping

---

Content/Forest/ButterflyStaff/ButterflyMinion.cs
Content/Forest/ButterflyStaff/ButterflyStaff.cs

- Removes existing distance check, adds in more robust check that mimics the Idle state change
- Teleport at large distance, stick to player, add vfx
- Rotates `stuckPos` when stuck to the player so it works with mounts or potentially mods like Overhaul

add proper distance check, vfx, rotate stuck position

---

Common/ModCompat/Classic/SpiritClassic.cs
Common/ProjectileCommon/BaseMinion.cs
Content/Jungle/Toucane/ToucanMinion.cs
Content/Jungle/Toucane/ToucaneItem.cs
Localization/zh-Hans/Mods.SpiritReforged.Items.hjson

- Increased Toucane minion fire rate by ~25%
- Increased Toucane damage (9 -> 12)
- Increased Toucane minion glide speed minimum & maximum velocity magnitude by 1
- Forced Toucane minion to retarget immediately on killing a target instead of flying away for some reason

increase toucane damage, fire rate, glide speed, fix retarget issue

---

Common/TileCommon/PresetTiles/SaplingTile.cs
Common/TileCommon/Tree/CustomTree.cs
Common/TileCommon/Tree/FertilizerGlobalProjectile.cs
SpiritReforged.cs

- Acacias are now affected by fertilizer and Axe of Regrowth

Increased custom tree functionality

---

Content/Desert/CactusStaff/CactusStaff.cs
Content/Forest/ButterflyStaff/ButterflyStaff.cs
Content/Forest/FairyWhistle/FairyWhistle.cs
Content/Forest/Misc/Cartographer.cs
Content/Forest/Misc/Hiker.cs
Content/Jungle/Toucane/ToucaneItem.cs
Content/Ocean/Items/JellyfishStaff/JellyfishStaff.cs
Content/Savanna/Items/Gar/QuenchPotion.cs
Content/Savanna/NPCs/PeevedTumbler/PeevedTumbler.cs
Content/Savanna/Tiles/AcaciaTree/AcaciaTree.cs
Localization/en-US/Mods.SpiritReforged.hjson
Localization/pt-BR/Mods.SpiritReforged.hjson
Localization/ru-RU/Mods.SpiritReforged.hjson
Localization/zh-Hans/Mods.SpiritReforged.hjson

- Living Baobab and Living Baobab Leaf wands now have a chance to drop from shook Acacia trees
- Reordered ingredients list for Quench Potion
- Cartographer and Hiker now animate in the Bestiary
- Made several summon weapons auto-reusable
- Included Peeved Tumbler item drops in the Bestiary and adjusted drop rates

Minor fixes

---

Content/Savanna/Items/CampfireSpit.cs

Tried to be flexible with RecipeGroups as well.

Added More Fire Spit Recipes

---

Content/Ocean/OceanPlayer.cs

Updated the Mod.Call, the existing one was deprecated in Thorium 1.4. Followed this guide: https://thoriummod.wiki.gg/wiki/Mod_Calls
(tested ingame)

Fixed Thorium/Deep Ocean music issue

---

Common/ModCompat/Classic/SpiritClassic.cs
Content/Forest/Misc/Maps/TornMapPiece.cs

Adds compatibility with Classic's `ContentDefinition` system
(https://github.com/GabeHasWon/SpiritMod/pull/53)

Classic item definition compatibility

---

Common/ProjectileCommon/BaseMinion.cs
Content/Jungle/Toucane/ToucanMinion.cs
Content/Ocean/Items/JellyfishStaff/JellyfishMinion.cs

Summons no longer need sight of enemies they're already pursuing.

Better minion targeting

---

Common/ModCompat/ThoriumCompat.cs
Content/Underground/Items/BigBombs/BoomShroom.cs
Content/Underground/Moss/Oganesson/OganessonMoss.cs
Content/Underground/Moss/Radon/RadonMoss.cs

- Embeds neon moss plants into the tiles they're anchored to
- Fixes some build errors

Minor update fixes

---

Content/Underground/Moss/MossWalkingEffects.cs

- Adds unique walking effects for each moss type

Moss Walking Effects

---

Common/TileCommon/ICutAttempt.cs
Common/WorldGeneration/Micropasses/Passes/NewNeonsMicropass.cs
Common/WorldGeneration/Micropasses/Passes/UndergroundHouseMicropass.cs
Content/Forest/Misc/Maps/TornMapPiece.cs
Localization/en-US/Mods.SpiritReforged.Generation.hjson
Localization/pt-BR/Mods.SpiritReforged.Generation.hjson
Localization/ru-RU/Mods.SpiritReforged.Generation.hjson
Localization/zh-Hans/Mods.SpiritReforged.Generation.hjson

Adds in the following to plain Underground houses:
1. [Wo]mannequins w/ gear
2. Signs
3. Loom rooms
and also reduces the cooldown of ICutAttempt tiles to 8 from 12 to work nicer with Minishark.

Underground house modifications

---

Common/ItemCommon/FloatingItem/FloatingItemWorld.cs
Content/Ocean/OceanGlobalNPC.cs

- Added a check for floating items to not spawn in tiles, I think this will fix the crossmod issue where floating items spawned in Fables grates? If not lmk
- Increased shark spawnrates slightly after a couple of complaints

Minor Tweaks

---

Common/TileCommon/PresetTiles/StatueTile.cs
Common/WorldGeneration/Micropasses/Passes/PotsMicropass.cs
Common/WorldGeneration/Micropasses/Passes/UndergroundHouseMicropass.cs
Content/Underground/Tiles/OrnatePots.cs
Content/Underground/Tiles/StuffedPots.cs

- Statues are now Spelunkerable
- Add shimmer checks for all the relevant pots
- Increased the rarities of uncommon/rare pots as per Dakota's Suggestions
- Added some loot to Ornate Pots
- Made Stuffed Pots drop regular cavern pot loot

Misc Fixes

---

Common/TileCommon/Placer.cs
Common/TileCommon/TileExtensions.cs
Common/WorldGeneration/Micropasses/Passes/PotsMicropass.cs
Common/WorldGeneration/Micropasses/Passes/PotteryStructureMicropass.cs
Content/Forest/Cloud/CloudGlobalTile.cs
Content/Ocean/OceanGlobalTile.cs
Content/Savanna/Tiles/ElephantGrass.cs
Content/Savanna/Tiles/SavannaGrass.cs
Content/Underground/Moss/LandscapingShears.cs
Content/Underground/Moss/Oganesson/OganessonMoss.cs
Content/Underground/Moss/Radon/RadonMoss.cs

- Adds `PlaceAttempt` struct and restructures `Placer` methods
- Makes requested changes pottery structure generation

Tile changes

---

Common/WorldGeneration/Micropasses/Passes/NewNeonsMicropass.cs
Content/Underground/Items/MossFlasks/FlaskArgon.cs
Content/Underground/Items/MossFlasks/FlaskHelium.cs
Content/Underground/Items/MossFlasks/FlaskKrypton.cs
Content/Underground/Items/MossFlasks/FlaskNeon.cs
Content/Underground/Items/MossFlasks/FlaskOganesson.cs
Content/Underground/Items/MossFlasks/FlaskRadon.cs
Content/Underground/Items/MossFlasks/FlaskXenon.cs
Content/Underground/Items/MossFlasks/MossFlask.cs
Content/Underground/Moss/Oganesson/OganessonPlants.cs
Content/Underground/Moss/Radon/RadonPlants.cs

- Moss flasks now replace foliage moss tiles
- Reduced moss flask damage to 10 and added new breaking dusts
- Oganesson and Radon mosses now have a 1/6 chance to generate

Moss changes

---

Common/ModCompat/Classic/ModifyNPCData.cs
Common/ModCompat/Classic/ObsoleteItem.cs
Common/ModCompat/Classic/SpiritClassic.cs
Common/ModCompat/CrossMod.cs
Common/ModCompat/FablesCompat.cs
Common/ModCompat/MusicDisplayCompat.cs
Common/ModCompat/NewBeginningsCompat.cs
Common/ModCompat/ThoriumCompat.cs
Common/WorldGeneration/Micropasses/Passes/SpecialPointMappingMicropass.cs
Common/WorldGeneration/Micropasses/Passes/UndergroundHouseMicropass.cs
Content/Forest/Cloud/Tiles/HangingCloudstalk.cs
Content/Jungle/Bamboo/Tiles/StrippedBamboo.cs
Content/Ocean/Hydrothermal/HydrothermalVentPlume.cs
Content/Ocean/Items/FishCrate.cs
Content/Ocean/Items/PirateKey.cs
Content/Ocean/Items/SunkenTreasure.cs
Content/Ocean/OceanGeneration.cs
Content/Ocean/OceanPlayer.cs
Content/Ocean/Tiles/Driftwood.cs
Content/Ocean/Tiles/Furniture/DriftwoodWorkBench.cs
Content/Savanna/Items/Fishing/SavannaCrate.cs
Content/Savanna/Items/Fishing/SavannaCrateHardmode.cs
SpiritReforged.cs

Makes Classic NPCs replaceable and includes some organizational changes.

Mod compatibility changes

---

Common/Easings/EaseFunction.cs
Common/ProjectileCommon/Abstract/BaseClubCommon.cs
Common/ProjectileCommon/Abstract/BaseClubProj.cs
Common/ProjectileCommon/Abstract/BaseClubVirtual.cs
Content/Desert/Scarabeus/Items/Projectiles/SunOrb.cs
Content/Particles/ImpactLine.cs
Content/Particles/ImpactLinePrim.cs
Content/Underground/Items/OreClubs/GoldClubProj.cs

-Adjusts the second swing to charge faster, do more knockback and damage, and tweaks the animation and angle range
-Changes hit effects, second swing hit has a unique visual

Gold hammer tweaks

---

Common/MathHelpers/CollisionCheckHelper.cs
Content/Underground/NPCs/Wheezer.cs

Wheezer now scans intermediate surface tiles rather than simply checking whether the target is in line of sight.

Smarter Wheezer collision check

---

Content/Underground/NPCs/DunceCrab.cs
Localization/en-US/Mods.SpiritReforged.NPCs.hjson

add dunce crab bestiary, moss eating behaviour, wheezer name fix

---

Common/WorldGeneration/Micropasses/Passes/MannequinInventories/IceMannequinInventory.cs
Common/WorldGeneration/Micropasses/Passes/MannequinInventories/MannequinInventory.cs
Common/WorldGeneration/Micropasses/Passes/MannequinInventories/UndergroundMannequinInventory.cs
Common/WorldGeneration/Micropasses/Passes/UndergroundHouseMicropass.cs

- Adds MannequinInventory system
- Moves Thorium's FrostburnPouch from wood houses to ice houses
- Adds ice house mannequin inventories

add ice house inventory, mannequin system

---

Common/ModCompat/CensusCompat.cs
Common/ModCompat/CrossMod.cs
Localization/en-US/Mods.SpiritReforged.NPCs.hjson
Localization/pt-BR/Mods.SpiritReforged.NPCs.hjson
Localization/ru-RU/Mods.SpiritReforged.NPCs.hjson
Localization/zh-Hans/Mods.SpiritReforged.NPCs.hjson

- Adds census compat for the pottery slime
- image in display text is not working

census compat

---

Content/Vanilla/Misc/VanillaNPCDialogue.cs
Localization/en-US/Mods.SpiritReforged.NPCs.hjson
Localization/pt-BR/Mods.SpiritReforged.NPCs.hjson
Localization/ru-RU/Mods.SpiritReforged.NPCs.hjson
Localization/zh-Hans/Mods.SpiritReforged.NPCs.hjson

- Adds 3 dialogue lines for NPCs in the savanna and dustorm
- more soon, just wanted to PR the structure of the GlobalNPC and make sure it looks okay
- anyone is welcome to add some for savanna or otherwise

Add VanillaNPCDialogue

---

Content/Forest/JinxBow/JinxBow.cs
Content/Forest/MagicPowder/Flarepowder.cs
Content/Jungle/Bamboo/Items/BambooKendoBlade.cs
Content/Ocean/Items/Rum/ExplosiveRum.cs
Content/Underground/Items/BombCannon.cs
Content/Underground/NPCs/MossSlimes/MossSlime.cs
Localization/en-US/Mods.SpiritReforged.hjson
Localization/pt-BR/Mods.SpiritReforged.hjson
Localization/ru-RU/Mods.SpiritReforged.hjson
Localization/zh-Hans/Mods.SpiritReforged.hjson

- Jinxbow: Arcane
- Powders: Arcane
- Kendo Blade: Slash
- Bomb Cannon: Explosive
- Moss Slime: Slime
- Explosive Rum: Explosive, Fire

Add Redemption Elements to New Items and NPCs

---

Content/Forest/MagicPowder/VexpowderBlue.cs
Content/Forest/MagicPowder/VexpowderRed.cs
Content/Ocean/Items/Rum/ExplosiveRum.cs
Content/Savanna/Items/Drypowder.cs
Content/Savanna/Tiles/SavannaCampfire.cs
Content/Underground/NPCs/MossSlimes/MossSlime.cs
Content/Underground/Tiles/AetherShipment.cs
Content/Vanilla/Leather/MarksmanArmor/AncientMarksmanHood.cs
Content/Vanilla/Leather/MarksmanArmor/AncientMarksmanLegs.cs
Content/Vanilla/Leather/MarksmanArmor/AncientMarksmanPlate.cs
Content/Vanilla/Leather/MarksmanArmor/LeatherHood.cs
Content/Vanilla/Leather/MarksmanArmor/LeatherLegs.cs
Content/Vanilla/Leather/MarksmanArmor/LeatherPlate.cs

- VexpowderBlue <-> VexpowderRed
- Explosive Rum -> Molotov
- Drypowder -> Purification Powder
- Savanna Campfire -> Aether Campfire
- Moss Slime -> Shimmer Slime
- Marksman Armor <-> Ancient Marksman
- Aether Shipments now drop the Thorium shimmer upgrades as well

Shimmer Recipes

---

Content/Forest/Misc/HerosMemorialStatue.cs
Content/Ocean/Tiles/PirateChest.cs
Content/Underground/Items/BoulderClub/Bowlder.cs
Content/Underground/Items/ExplorerTreads/ExplorerTreadsItem.cs
Content/Underground/Items/Zipline/ZiplineGun.cs
Content/Vanilla/Food/RawFish.cs
Content/Vanilla/Misc/AnglerQuestRewards.cs

- Adds AnglerQuestRewards and the following items as rewards: Sunken Treasure, Fishing Lure
- Added following items to Gold Crate: Rail-Gun, Explorer's Treads, Bowlder
- Added Hero's Memorial recipe
- Raw Fish now makes 2 Cooked Fish

Small Changes

---

Content/Underground/Tiles/AetherShipment.cs
Content/Underground/Tiles/SilverPlatters.cs
Content/Underground/Tiles/WickerBaskets.cs

- Adds Fruit, Food, and Drink from Thorium and MoR into Silver Platters and Wicker Baskets where applicable.

Crossmod food
